name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:

    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.2, 7.3, 7.4]

        os: [ubuntu-latest]

        dependencies: [locked]

        experimental: [false]

        include:
          - php-version: 7.4
            dependencies: highest
            os: ubuntu-latest
            experimental: false

          - php-version: 7.4
            os: windows-latest
            dependencies: locked
            experimental: false

          - php-version: 7.4
            os: macos-latest
            dependencies: locked
            experimental: false

          # - php-version: 8.0
          #   dependencies: highest
          #   os: ubuntu-latest
          #   experimental: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Composer
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, ctype, dom, fileinfo, intl, gd, json, mbstring, pdo, pdo_sqlite, openssl, sqlite, xml, zip
          coverage: none

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.local', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Generate key
        run: php artisan key:generate

      - name: Install NPM
        run: npm install

      - name: Compile assets
        run: npm run production

      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
